#!/usr/bin/env bash
# Interactive, resumable recorder for the corpus. Each sub-corpus is a folder = manifest.json (a
# clips[] array) + flat <id>.wav (16 kHz mono). For each clip it shows the text + group/tags, waits
# for Enter to start, records mic → <id>.wav, waits for Enter to stop. Ctrl-C any time and re-run —
# already-recorded clips are skipped, so a corpus is recorded over several sittings.
#
# Default records the tiered STT engine corpus (stt/). --commands records the spoken-command
# regression cases (commands/), replayed by `KeyScribe --commands-check corpus/commands`. --voices
# records YOUR takes for the voice study (voices/ — the source=human clips; the synthetic voices are
# generated by gen_corpus.py, not recorded here).
#
# Usage:
#   bash corpus/record.sh --status                 # per-tier progress, record nothing
#   bash corpus/record.sh                          # record every un-recorded stt clip (all tiers)
#   bash corpus/record.sh --tier T1                # record only the un-recorded Tier 1 clips
#   bash corpus/record.sh --device :2 --tier T2    # pick a mic, one tier
#   bash corpus/record.sh 14 c27 c82               # (re)record specific ids, overwriting them
#   bash corpus/record.sh --commands [--status]    # command-case corpus (progress / record)
#   bash corpus/record.sh --commands vb01 np_period # (re)record specific command ids
#   bash corpus/record.sh --voices [--status]      # your human takes for the voice study
#
# Find your mic's avfoundation index:  ffmpeg -f avfoundation -list_devices true -i ""
set -euo pipefail
cd "$(dirname "$0")"

DEVICE=""   # empty = auto-resolve to the system default input mic BY NAME (see below)
TIER=""
STATUS_ONLY=0
COMMANDS=0
VOICES=0
WANT=()   # explicit ids to (re)record; non-empty = overwrite those, ignore tier/skip

while [ $# -gt 0 ]; do
  case "$1" in
    --status)   STATUS_ONLY=1; shift ;;
    --commands) COMMANDS=1; shift ;;
    --voices)   VOICES=1; shift ;;
    --tier)     TIER="$2"; shift 2 ;;
    --device)   DEVICE="$2"; shift 2 ;;
    :*)         DEVICE="$1"; shift ;;          # bare ":N" still means device (back-compat)
    -*)         echo "unknown flag: $1" >&2; exit 2 ;;
    *)          WANT+=("$1"); shift ;;
  esac
done

# Each sub-corpus is a folder = manifest.json (clips[]) + flat <id>.wav. --commands records the
# spoken-command cases (commands/); --voices records YOUR takes for the voice study (voices/, the
# clips with source=human); default records the tiered STT engine corpus (stt/). MODE/MANIFEST/OUTDIR
# flow through both the extraction and the --status readouts below.
if [ "$COMMANDS" -eq 1 ]; then
  MODE="commands"; MANIFEST="commands/manifest.json"; OUTDIR="commands"
elif [ "$VOICES" -eq 1 ]; then
  MODE="voices"; MANIFEST="voices/manifest.json"; OUTDIR="voices"
else
  MODE="stt"; MANIFEST="stt/manifest.json"; OUTDIR="stt"
fi

command -v ffmpeg >/dev/null || { echo "ffmpeg not found (brew install ffmpeg)"; exit 1; }

# Resolve the avfoundation capture target. Selecting by numeric index (":0") is unstable: a virtual
# audio device (a screen-recorder / meeting mic, e.g. "Achelous Microphone") can insert itself at
# index 0 and push the real mic down, so ":0" silently records the virtual device — pure silence.
# Default to the *system default input device by NAME*, which avfoundation resolves regardless of
# index. An explicit --device (index or name) is always honored verbatim.
default_input_name() {
  system_profiler SPAudioDataType 2>/dev/null | awk '
    /^ {8}[A-Za-z].*:$/ { name=$0; sub(/^ +/, "", name); sub(/:$/, "", name) }
    /Default Input Device: Yes/ { print name; exit }'
}
if [ -z "$DEVICE" ]; then
  micname="$(default_input_name)"
  if [ -n "$micname" ]; then
    DEVICE=":$micname"
  else
    DEVICE=":0"
    echo "⚠️  could not resolve the default input device — falling back to index :0" >&2
  fi
fi

# manifest clips[] → US-separated rows: id \x1f group \x1f tags \x1f text \x1f note  (a non-whitespace
# separator so an empty middle field — e.g. no tags — is preserved, not collapsed by read's IFS).
# STT group=tier, filtered by --tier; commands=cmd; voices=voice and limited to source=human.
python3 - "$TIER" "$MANIFEST" "$MODE" <<'PY' > /tmp/bench_prompts.tsv
import json, sys
want_tier, manifest, mode = sys.argv[1], sys.argv[2], sys.argv[3]
for c in json.load(open(manifest))["clips"]:
    if mode == "voices" and c.get("source") != "human":
        continue
    stt = (c.get("checks") or {}).get("stt") or {}
    group = stt.get("tier", "cmd" if mode == "commands" else ("voice" if mode == "voices" else "?"))
    if mode == "stt" and want_tier and group != want_tier:
        continue
    tags = ",".join(c.get("tags", []))
    note = (c.get("note") or "").replace("\t", " ").replace("\n", " ")
    print("\x1f".join([c["id"], group, tags, c["text"], note]))
PY

want_match() {
  [ ${#WANT[@]} -eq 0 ] && return 0
  for w in "${WANT[@]}"; do [ "$w" = "$1" ] && return 0; done
  return 1
}

# --status: recorded/total progress, then exit. STT is per-tier; commands/voices are a flat count.
if [ "$STATUS_ONLY" -eq 1 ]; then
  python3 - "$MANIFEST" "$OUTDIR" "$MODE" <<'PY'
import json, os, sys
from collections import OrderedDict
manifest, outdir, mode = sys.argv[1], sys.argv[2], sys.argv[3]
clips = json.load(open(manifest))["clips"]
if mode == "voices":
    clips = [c for c in clips if c.get("source") == "human"]
def wav(c): return os.path.join(outdir, c.get("file", c["id"] + ".wav"))
if mode == "stt":
    tiers = OrderedDict()
    for c in clips:
        t = ((c.get("checks") or {}).get("stt") or {}).get("tier", "?")
        d = tiers.setdefault(t, [0, 0]); d[1] += 1
        if os.path.exists(wav(c)): d[0] += 1
    gt = [0, 0]
    print("tier   recorded / total")
    for t, (h, n) in tiers.items():
        print(f"  {t:<4} {h:>4} / {n}"); gt[0] += h; gt[1] += n
    print(f"  {'all':<4} {gt[0]:>4} / {gt[1]}")
else:
    have = [c for c in clips if os.path.exists(wav(c))]
    print(f"{mode} clips recorded {len(have)} / {len(clips)}")
missing = [c["id"] for c in clips if not os.path.exists(wav(c))]
if missing:
    print("\nnext un-recorded:", " ".join(missing[:12]) + (" …" if len(missing) > 12 else ""))
else:
    print("\nall clips recorded ✓")
PY
  exit 0
fi

echo "Recording from avfoundation device '$DEVICE'  (list devices: ffmpeg -f avfoundation -list_devices true -i \"\")"
echo "First run may prompt your terminal for microphone permission — grant it, then re-run."
echo "While recording: ⏎ saves · type r then ⏎ to re-record · q then ⏎ to quit · Ctrl-C discards."
[ -n "$TIER" ] && echo "Tier filter: $TIER"
[ ${#WANT[@]} -gt 0 ] && echo "Re-recording (overwrite): ${WANT[*]}"

pid=""
out=""
trap 'echo; [ -n "$pid" ] && kill -INT "$pid" 2>/dev/null; [ -n "$out" ] && rm -f "$out"; echo "interrupted — discarded ${out:-current clip}"; exit 130' INT

# Count how many in the (filtered) set still need recording, for an [n/total] progress readout.
total=$(wc -l < /tmp/bench_prompts.tsv | tr -d ' ')
idx=0
while IFS=$'\x1f' read -r id tier tags text note; do
  idx=$((idx + 1))
  want_match "$id" || continue
  out="${OUTDIR:+$OUTDIR/}$id.wav"
  # Full walk skips existing; explicit ids always overwrite.
  if [ ${#WANT[@]} -eq 0 ] && [ -f "$out" ]; then continue; fi
  echo
  echo "[$idx/$total] $id · $tier${tags:+ · $tags}"
  [ -n "$note" ] && echo "    how to read it: $note"
  echo "    READ ALOUD:  \"$text\""
  # Re-record loop: a clip stays current until it is saved, skipped, or quit.
  while true; do
    rm -f "$out"
    read -r -p "  ⏎ to START · s skip · q quit … " ans </dev/tty
    case "$ans" in
      q|Q) echo "  quit."; exit 0 ;;
      s|S) echo "  ↷ skipped $id"; break ;;
    esac
    ffmpeg -nostdin -hide_banner -loglevel error -f avfoundation -i "$DEVICE" -ac 1 -ar 16000 "$out" &
    pid=$!
    read -r -p "  ● recording — ⏎ STOP · r ⏎ re-record · q ⏎ quit … " ans </dev/tty
    kill -INT "$pid" 2>/dev/null || true
    wait "$pid" 2>/dev/null || true
    pid=""
    case "$ans" in
      r|R) echo "  ↻ re-recording ${id}…"; continue ;;
      q|Q) rm -f "$out"; echo "  quit."; exit 0 ;;
    esac
    # Catch silent failures: too-small file (no mic permission / bad device) OR a full-length file of
    # pure silence (wrong/virtual device captured — bytes look fine but every sample is at the floor).
    size=$(stat -f%z "$out" 2>/dev/null || echo 0)
    if [ "$size" -lt 4000 ]; then
      echo "  ⚠️  $out is ${size} bytes — recording FAILED (check mic permission / device index). Retrying."
      continue
    fi
    mean=$(ffmpeg -nostdin -hide_banner -i "$out" -af volumedetect -f null - 2>&1 \
           | sed -n 's/.*mean_volume: \(-*[0-9.]*\) dB.*/\1/p' | head -1)
    if [ -n "$mean" ] && awk "BEGIN{exit !($mean <= -80)}"; then
      echo "  ⚠️  $out is SILENT (${mean} dB) — '$DEVICE' captured no audio. Retrying."
      echo "      A virtual mic may have hijacked the input; pick the real mic with --device, e.g.:"
      echo "        ffmpeg -f avfoundation -list_devices true -i \"\"   # find your mic's index/name"
      continue
    fi
    echo "  ✓ saved $out (${size} bytes, ${mean:-?} dB)"
    break
  done
done < /tmp/bench_prompts.tsv

echo
echo "Done with this pass. Re-run any time — recorded clips are skipped."
case "$MODE" in
  commands)
    echo "Progress: bash corpus/record.sh --commands --status"
    echo "Then replay the command cases through the real no-LLM pipeline:"
    echo "  KeyScribe --commands-check corpus/commands" ;;
  voices)
    echo "Progress: bash corpus/record.sh --voices --status"
    echo "Then dump raw transcripts across engines:"
    echo "  KeyScribe --benchmark corpus/voices --raw" ;;
  *)
    echo "Progress: bash corpus/record.sh --status"
    echo "Then compare engines over these recordings:"
    echo "  bash corpus/compare.sh" ;;
esac
